import { createSlice, nanoid } from "@reduxjs/toolkit"

// Initialize the todos state with stored data or a default todo
const initialState = {
  todos: localStorage.getItem("todos") 
    ? JSON.parse(localStorage.getItem("todos"))
    : [{id: 1, text: "Hello World"}]
}

// Create a slice for managing todo-related state and actions
export const todoSlice = createSlice({
  name: "todo",
  initialState,
  reducers: {
    // Add a new todo item to the state
    addTodo: (state, action) => {
      const todo = {
        id: nanoid(), 
        text: action.payload
      } 
      state.todos.push(todo);
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },
    // Remove a todo item from the state based on the provided id
    removeTodo: (state, action) => {
      state.todos = state.todos.filter(todo => todo.id !== action.payload);
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },
  },
});

// Extract the generated action creators for addTodo and removeTodo
export const { addTodo, removeTodo } = todoSlice.actions 

// Export the reducer function generated by createSlice
export default todoSlice.reducer;